[connections.default]
account = "vx70256-sw09563"
user = "ML_LAYER_USER"
role = "ML_LAYER_ROLE"
warehouse = "ML_LAYER_WH"
database = "ML_LAYER_DB"
authenticator = "SNOWFLAKE_JWT"
private_key_path = ".keys/rsa_key.p8"